name: Sync Charts

on:
  push:
    branches:
      - master
    paths:
      - '**'
#      - 'charts/**'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ github.repository }}'
          separator: '/'

      - name: Sync to openyurt-helm Repo
        env:
          REPOSITORY_OWNER: ${{ steps.split.outputs._0 }}
          SSH_DEPLOY_KEY: ${{ secrets.SYNC_CHARTS_SECRET }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          TAG: ${{ steps.get_version.outputs.TAG }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/lib/sync-charts.sh
